# Generated by Django 3.2.9 on 2021-11-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MRCSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=4096)),
                ('question', models.CharField(max_length=720)),
                ('answer', models.CharField(max_length=320)),
                ('dataset_key', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SystemOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_question', models.CharField(max_length=720)),
                ('system_key', models.CharField(max_length=16)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hahaweb.mrcsample')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hahaweb.annotator')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hahaweb.systemoutput')),
            ],
        ),
    ]
