import React from 'react';
import { Row, Descriptions, Layout } from 'antd';
const { Header, Content, Footer, Sider } = Layout;



export default class InstructionDashBoard extends React.Component {
  constructor() {
    super()
    this.state = {
      chartData: [ ]
    }
  }

  render() {
    return (
      <div>
        <Footer style={{ textAlign: 'center' }}>Anonymized Author © Nov. 2021 </Footer>
        <Row
          style={{
            background: '#fff',
            padding: '16px 16px 0',
            marginBottom: '32px'
          }}
        >
            <Descriptions
              title="Human Annotation Web Application"
              layout="vertical"
              bordered={false}
              column={1}
            >
              <Descriptions.Item label="Overriew">
                Firstly, you will be provided a passeage, a question and a text span to answer this question based the passage.
                <br />
                Then, you will see questions generated by different neural models and be asked to annotate their quality from the following three dimensions.
              </Descriptions.Item>
                
              <Descriptions.Item label="Grammaticality">
                It checks whether a question is <strong>well-formed</strong>. Annotators are asked to rate a sample as 3 for "no grammatical errors", 2 for "partially grammatical errors but able to infer actual meaning", and 1 for "unacceptable".
              </Descriptions.Item>

              <Descriptions.Item label="Answerability">
                It checks whether a question is <strong>answerable</strong> according to the presence and correctness of important information such as named entities, content (relation) words, and question types. Annotators are asked to rate a sample as 3 for "all important information is present", 2 for "some important information is missing", and 1 for "all important information is missing".
              </Descriptions.Item>

              <Descriptions.Item label="Relevance">
                It checks whether a question is <strong>relevant</strong> to the context and it can be answered by the input answer span correctly. Annotators are asked to rate a sample as 3 for "completely relevant", 2 for "slightly irrelevant but able to answer the question", and 1 for "totally irrelevant".
              </Descriptions.Item>
            </Descriptions>
        </Row>
      </div>
    )
  }
}
